# Generated by Django 5.2.6 on 2025-11-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_carrito', '0007_add_stripe_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(default='stripe', max_length=50),
        ),
    ]
